### ISSUE TITLE
TW Presidential Hackathon

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#743]
A/B Street is participating in the [Taiwan presidential hackathon](https://presidential-hackathon.taiwan.gov.tw/en/international-track/)! The new "ungap the map" bike network tool is our focus, as a way to help citizens & advocacy groups push governments for alternatives to driving in cities. The tool is related to [SDG 11](https://sdgs.un.org/goals/goal11) and [SDG 13](https://sdgs.un.org/goals/goal13).

I'll use this issue to organize project management.

# Work plan

Summarizing from a spreadsheet, subject to change:
- 19-27 Aug: Prep for the Aurora workshop at Lantern: #725.
- 30 Aug - 3 Sept: Address UI feedback so far, improve road editor
- 6 - 10 Sept: Proposal sharing
- 13 - 17 Sept: Flesh out the routing tool, and work on mode shift #448 to predict how many driving trips might change if infrastructure is built
- 20 - 24 Sept: Add basic carbon emissions modeling
- 27 Sept - 1 Oct: Deploy to more cities. Depending on connections we can make, Tempe, NYC, and Taipei are possibilities.
- 4 - 8 Oct: Improve performance of tool, especially on the large Seattle-wide map
- 11 - 14 Oct: Write documentation, prepare for final demo, catch up on any final polishing needed.

# Feedback from judges

Two people mentioned tying the work into climate change more directly:

- "The stackholders can analyze the carbon saved by this platform"
- "-No use or generate of data on climate change. (traffic data is used instead) A suggested improvement would be to calculate the carbon emission reduction from the proposed change. (calculate measurable impacts)"

And in response, I think I'll prioritize "testing" somebody's proposed bike network by
1) Seeing how many short driving trips would make use of new infrastructure - #448 
2) Adding a basic carbon emissions model and estimating savings from people making different travel choices

**Comment by dabreegster** [comment]
# Tasks

I'm bad at keeping TODO lists in one place, but I'll try to consolidate here. These come from #725 and https://github.com/a-b-street/abstreet/projects/12...

## Solidify map model

- [ ] Make progress on snapping cycleways, #330 
- [ ] Write up an article clearly explaining the snapping problem, to communicate to the OSM community better
- [ ] Consider merging divided highways like Aurora into one object with an explicit median, so proposals can consider the entire right-of-way width

## Road editor UI

- [ ] More lane width pre-sets, probably based on NACTO
- [ ] Individual edits are slow -- adjusting lane width using the spinner really reveals this
- [ ] Consult with Yuwen about ideas to simplify the controls, like making lane types a dropdown or hiding the "add new lane" while selecting a current lane

## Explore mode

- [ ] Improve color scheme for showing hierarchy of bike lane types
- [ ] Improve highlighting of road types
- [ ] Show elevation data while zoomed in?
- [ ] Possibly add a layer with historic collision data
- [ ] Bug: Opening previous proposal has error message sometimes

## Create new bike lanes tool

- [ ] Click and drag control to paint?
- [ ]  Be more clear that the "create new lanes" tool will only modify existing lanes, not expand width. Need a clear error state. And make sure it doesn't expand width -- parking -> bike lane + separators currently looks too wide.
- [ ] Test everything in left-handed maps

## Plan a route

- [ ] Just click to add waypoints
- [ ] Let user set their preferences, probably based on some tuned pre-sets (avoid hills, avoid stressful roads, bravely blaze through anything to be fast)
- [ ]  Automatically show alternate routes (the slow-but-safe route, vs the direct-but-scary route)
- [ ] Show how the route could change with a proposal?
- [ ] Watch the route: just animate somebody walking/biking/driving along the route, using the traffic sim, and follow along
- [ ] Save routes that the user draws, and browse them later. The user thinks of these as "test cases"

## Sharing proposals

- [ ] Get the "share URL" function working end-to-end... update the URL correctly
- [ ] Find a cheaper SQL host
- [ ] Get a manual moderation workflow working
- [ ] Add a "browse proposals" UI

## Advocacy

- [ ] Test the tool end-to-end by mocking up Seattle's basic bike network
- [ ] Mock up my own ideas for extensions to the network
- [ ] Ask SNG to use this for their "ungap the map" campaign
- [ ] Establish a connection with NYC / TransAlt

**Comment by dabreegster** [comment]
# Status update from week 2

The original plan was to address the most urgent UX feedback from the workshop. Some of that has happened:
- #744 fixed the confusing highlighting and made road labels always legible
- Adding waypoints when drawing a route is now just done by clicking

While I was fixing up the route tool, I started on some stuff from week 4:
- Saving routes, so the user can define them as "test cases," then edit the bike network, and see how things work before/after
- Showing elevation along the route both on the map and in the line plot

And I started digging into performance issues and trimming down the size of the region-wide maps in #746. I think there's some invasive refactoring work there that I want to work on early...

And finally, I spend lots of time writing up a [project demo reel & retrospective](https://a-b-street.github.io/docs/project/retrospective/index.html) and an article diving into one of the hardest problems A/B Street tackles, [making intersection geometry](https://a-b-street.github.io/docs/tech/map/geometry/index.html). These aren't directly related to the hackathon, but are increasingly vital for the project's long-term health -- I want other people to understand how tricky parts of the code work.

The stated plan for week 3 is proposal sharing. Due to an upcoming conference deadline, I will spend more time writing docs/articles, and also keep pushing forward this performance and route tool work. I think the m.v.p. for sharing shouldn't take more than a day or two anyway.

I'll update with a link to the new web version when I release tomorrow. But some of the new features in the route tool are demoed below:
![screencast](https://user-images.githubusercontent.com/1664407/132113467-b299c767-ec63-49ed-9d60-0a54707d5154.gif)

**Comment by dabreegster** [comment]
# Status update from week 3

I got fairly off-track this week due to interviews and preparing for a talk at the [SUMO conference](https://www.eclipse.org/sumo/conference) tomorrow. I wound up writing 3 things this week, not directly related to the hackathon's scope, but again useful for ensuring the project could continue without my knowledge.
- Slides for the SUMO conference: https://docs.google.com/presentation/d/1_xaR0LQCkZVhcxIep1YgzWm18NVxhGwZVHh-tNfDpjY/edit?usp=sharing
- A deep dive into generating intersection geometry. Nearly ready to widely publish this! https://a-b-street.github.io/docs/tech/map/geometry/index.html
- A deep dive into how the movement in the traffic simulation works: https://a-b-street.github.io/docs/tech/trafficsim/discrete_event/index.html

Direct work on the bike network tool from this week included a huge breakthrough for performance after editing the map (#748) and some help from Michael polishing the route tool (#751). New build at http://abstreet.s3-website.us-east-2.amazonaws.com/0.2.58/abstreet.html?--ungap&system/us/seattle/maps/udistrict.bin

The plan for this week is to continue on the routing tool and mode shift. I hope to focus on code, not writing, this week finally! I'll also pay down the debt of sharing map edits from last week.

**Comment by dabreegster** [comment]
# Status update from week 4

Falling _slightly_ behind the original schedule, but I've never been great at predicting when things will happen. A fair bit happened this week -- the routing tool got lots more detail added and better management of saved routes. There were some more performance improvements, for pathfinding and for serving the website through a CDN. The quick-sketch tool now works in the UK and other left-handed maps. And, unrelated to the bike network tool, I published the article about intersection geometry and got [quite a strong response](https://news.ycombinator.com/item?id=28568081) online.

Also, yesterday I attended [DemocracyLab's national day of civic hacking](https://www.democracylab.org/events/ndoch-2021) and had the pleasure of 3 people joining for the day to work on the tool! Mara redesigned the route tool, pretty much solving the UX problems with the panels covering up the map: https://www.figma.com/file/6WMaKr49CHCHv5B98Ytmli/Map?node-id=0%3A1
![Screenshot from 2021-09-18 15-15-30](https://user-images.githubusercontent.com/1664407/133948542-3599f4aa-d84a-4c3c-943f-d90156fbf25f.png)
And Jennifer started helping with the quick sketch tool, finding lots of problems where the automated changes would actually require repaving the road and changing its curb-to-curb width. There's a design to deal with this problem more clearly:
https://www.figma.com/file/TrOmz7fq53l80yNHUelLgt/AB-street-mockups?node-id=0%3A1
![Screenshot from 2021-09-18 15-20-04](https://user-images.githubusercontent.com/1664407/133948584-124b40e3-8212-467d-929e-7309138d61bb.png)

So I guess this week my priorities are:
1) Take the next steps on the mode shift tool and integrate it to the bike network UI. I'm now understanding this as a sort of "large-scale test case" for the user's proposed bike network. The existing route UI is the "small scale" test.
2) Then use the results of the mode shift to calculate carbon savings. I'm _hoping_ this is just a matter of plugging in total mileage into a formula and making some reasonable guesses about vehicle types.
3) Implement Mara's designs
4) If there's time, catch up on the proposal sharing work.

**Comment by dabreegster** [comment]
# Status update from week 5

I made lots of progress on first 3 tasks from last week -- most notably, the tool now looks at an existing travel demand model and predicts how many people will switch from driving to biking, and what that looks like in terms of CO2 emissions. There are loads of assumptions in this calculation, but the tool exposes a way to interactively tune these parameters.

Try it out: http://play.abstreet.org/0.2.60/abstreet.html?--ungap&system/us/seattle/maps/udistrict.bin
Watch a ~10 min (very unedited) demo of the tool so far: https://www.youtube.com/watch?v=o6_SGzIYwLk

I also started a very simple prototype of a related tool to help UK cities plan low-traffic neighborhoods to reduce [rat running](https://en.wikipedia.org/wiki/Rat_running).

Try it: http://play.abstreet.org/0.2.60/abstreet.html?--ltn&system/gb/leeds/maps/north.bin
Quick video explanation: https://www.youtube.com/watch?v=l_klZxlKmXU

**Comment by dabreegster** [comment]
# Status update from week 6

The [FOSS4G](https://callforpapers.2021.foss4g.org/foss4g2021/talk/CA8M8U/) conference and more interviews ate most of my time this week. I did implement alternate low-stress or low-hill routes, and then started down the rabbit hole of #763 to pay down technical debt for how complicated it is to manage selection and dragging for different waypoints and alternate routes.

New build: http://play.abstreet.org/0.2.61/abstreet.html?--ungap&system/us/seattle/maps/udistrict.bin

With 2 weeks left, ordered priorities become:
1) Get the absolute mvp for sharing proposals working (although I'd really like to properly work on #765)
2) Use the tool myself and record a bunch of example network extensions, and not get too distracted by all the adjustments to how the tool works that I'll inevitably imagine...
3) Make progress on #746. The mitigation if this falls through is just asking people to download the tool and run locally. It's only a big problem in the web version.
4) Start writing all the final deliverable system docs
5) Keep polishing UI -- Michael's alternate route feedback, the mode shift page, route details particularly
